-- https://school.programmers.co.kr/learn/courses/30/lessons/164668
SELECT USER_BOARD.USER_ID, USER_BOARD.NICKNAME, ITEM_BOARD.TOTAL_SALES
FROM (SELECT SUM(PRICE) AS "TOTAL_SALES", WRITER_ID
        FROM USED_GOODS_BOARD
        WHERE STATUS = "DONE"
        GROUP BY WRITER_ID
        HAVING SUM(PRICE) >= 700000) AS ITEM_BOARD inner join USED_GOODS_USER AS USER_BOARD
ON ITEM_BOARD.WRITER_ID = USER_BOARD.USER_ID
ORDER BY TOTAL_SALES ASC